# Generated by Django 5.1.7 on 2025-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='category.jpg', null=True, upload_to='course-file'),
        ),
    ]
